name: fileaudioplayer_example
description: Demonstrates how to use the fileaudioplayer plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fileaudioplayer:
    path: ../

  cupertino_icons: ^0.1.3
  path_provider: ^1.6.5
  path: ^1.6.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/