name: fileaudioplayer
description: Audio player for local files. This plugin have ducking support to reduce the main audio volume while playing background music
version: 0.0.9
homepage: https://github.com/tapeo/file_audio_player

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: it.matteoricupero.fileaudioplayer
        pluginClass: FileaudioplayerPlugin
      ios:
        pluginClass: FileaudioplayerPlugin